export const POST_USER_REQUEST = "POST_USER_REQUEST";
export const POST_USER_SUCCESS = "POST_USER_SUCCESS";
export const POST_USER_FAILURE = "POST_USER_FAILURE";
export const CLEAR_LOGIN_REQUEST = "CLEAR_LOGIN_REQUEST";
